### ISSUE TITLE
List/head is O(N)

### ISSUE THREAD

**Issue by nponeccop** [groupoid/om#10]

**Comment by 5HT** [comment]
It is always so in Church-like encodings.
In Scott encoding generated List/head would be different.

**Comment by zraffer** [comment]
The problem is also specific for strict functions (= F-algebra structure) to be passed to the recursor. `List/head` made by a lazy algebra will run in `O(1)` even in Church's encoding. However `List/id` will be `O(N)`, so it requires both a new encoding and a lazy structure.

**Comment by nponeccop** [comment]
Well, it's a large issue so we can split it into several smaller ones. 
- What about performance of `id = \a -> a`? Does it copy the term or a reference to it? What about `foo a = bar a a`? Does it copy `a` or not?
- What about compositions like `filter . map`? Do they fuse naturally due to normalization or we should write a fuser at some point?
- what about colists? Do they have same set of problems with `head`/`id` and composition/fusion?

**Comment by zraffer** [comment]
- By the way, representations of lists/colists seem to be an issue of EXE, not OM itself, don't them?
- Lamping or other algorithms are to be issues of OM, but if we were implementing them on the top of Erlang/BEAM/LING, we obviously will not be bounded to underlying CBV implementation.

**Comment by 5HT** [comment]
Unfortunately we can't move the Issue to EXE, so talking here is ok.

**Comment by nponeccop** [comment]
@5HT The common practice is to create a new issue (issues?) in EXE and reference this one there.

@zraffer 
- OM is not set in stone and to be changed if upper levels cannot be implemented efficiently on top of it
- The lower level is not set in stone either as we can choose different translations into VM if efficiency requires it.

**Comment by 5HT** [comment]
All additions to CoC is mostly a syntax sugar. Except Fix axiom. So there is a very little chance we need to extend OM core, as we intentionally moved encoding implementations to EXE macro system.

**Comment by nponeccop** [comment]
It's true only if it's actually possible to fix these problems without changing OM. At this point I'm not sure.

And of course even an inefficient implementation of our calculus is worth a paper. But if `if` always evaluates both branches or lists are always scanned fully, it's practical usefullness would be low.

So this one is essentially a low-priority issue for Om, as at first you need to implement the calculus, and then to see if it fits in the production loop or you needs another one.

I'd focus on getting a working implementation of Om and a paper on arXiv for now.

**Comment by 5HT** [comment]
I understand and agree on inability of current Morte's Church-like encoding to satisfy production needs.
The encoding problem is a central problem of Groupoid Infinity, Inc.
And we definitely need to refresh the Om paper and its structure.
