### ISSUE TITLE
Examples of normalization corner cases

### ISSUE THREAD

**Issue by nponeccop** [groupoid/om#26]
A term that looks much worse after normalization. E.g. the one that uses sharing extensively.

It is not a counterexample to normalization per se, but to normalization seen as optimization or god forbid superoptimization.

**Comment by nponeccop** [comment]
There should be 3 examples:

- an example that multiplicates its argument due to sharing (e.g. `let b = a + a in ...`) so it gets much worse when the sharing is lost
- an example that performs a long computation but don't consume much space
- an otherwise normal example which consumes much space during execution but otherwise normal (e.g. tetration of 10)

**Comment by 5HT** [comment]
https://maxim.livejournal.com/494414.html
